services:
  db:
    image: postgres:16-alpine
    container_name: database
    restart: unless-stopped
    env_file:
      - ./backend/${BACKEND_ENV_FILE:-.env}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
      secrets:
        - backend_env
    container_name: backend
    restart: on-failure
    depends_on:
      - db
    env_file:
      - ./backend/${BACKEND_ENV_FILE:-.env}
    networks:
      - network
    ports:
      - "3000:3000"


volumes:
  postgres_data:

secrets:
  backend_env:
    file: ./backend/${BACKEND_ENV_FILE:-.env}

networks:
  network:
    driver: bridge
