services:
  db:
    image: postgres:16-alpine
    container_name: database
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
      secrets:
        - backend_env
    container_name: backend
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    command: >
      sh -c "export DATABASE_URL=postgresql://$${POSTGRES_USER}:$${POSTGRES_PASSWORD}@db:5432/$${POSTGRES_DB}?schema=public
      && npm run prisma:migrate:deploy
      && npm run start:prod"

volumes:
  postgres_data:

secrets:
  backend_env:
    file: ./backend/.env
