services:
  db:
    image: postgres:16-alpine
    container_name: database
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-scenor_admin} -d ${POSTGRES_DB:-scenor}"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
      secrets:
        - backend_env
    container_name: backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-scenor_admin}:${POSTGRES_PASSWORD:-scenor_admin}@db:5432/${POSTGRES_DB:-scenor}?schema=public
    ports:
      - "3000:3000"
    command: sh -c "npm run prisma:migrate:deploy && npm run start:prod"

volumes:
  postgres_data:

secrets:
  backend_env:
    file: ./backend/.env
