// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from 'dotenv';
import { defineConfig, env } from "prisma/config";

const explicitFile = process.env.ENV_FILE?.trim();
const nodeEnv = process.env.NODE_ENV?.trim();

const envFiles = explicitFile
  ? [explicitFile]
  : [
      ...(nodeEnv === 'prod' || nodeEnv === 'production' ? ['.env.prod'] : []),
      ...(nodeEnv ? [`.env.${nodeEnv}`] : []),
      '.env',
    ];

for (const filePath of [...new Set(envFiles)]) {
  loadEnv({ path: filePath });
}

export default defineConfig({
  schema: "prisma/",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
